### PR TITLE
Audit HOCs to match contracts

### PR DESCRIPTION
**Pull request by rbharath**
This PR bumps the version to 3.0.1 from 2.0.1 (major version bump since breaking changes)

### CODE REVIEW

**Review by robrobbins — APPROVED** [review]

**Comment by robrobbins** [comment]
merge it after you push 3.0.1 to PYPI test (make sure their verz is 3.0.1)

**Comment by rbharath** [comment]
I removed the version bump from this PR since I found a number of mismatches between the HOCs and the contracts. I've fixed these issues in this PR. I'll open a new version bump PR once these fixes are merged in

**Comment by rbharath** [comment]
Added version bump to 3.0.1 back in here so we don't have to wrangle multiple PRs

**Comment by rbharath** [comment]
Merging this PR in after talking with @robrobbins offline since changes are minimal and travis is green.

**Pull request merged**
