### PR TITLE
Add getters for symbol/decimals.

### PR DESCRIPTION
**Pull request by rbharath**
Adds getters for the symbol/decimals for the Token higher order contracts along with tests.

### CODE REVIEW

**Comment by rbharath** [comment]
Also, this does a version bump on `web3.py` to 5.0.0b2

**Review by robrobbins — CHANGES_REQUESTED** [review]
put the 2 methods in the super so that you only need to write them once and take them out of the child classes

**Comment by robrobbins** [comment]
and update requirements.txt (or should it be removed?)

**Comment by robrobbins** [comment]
Not merging just yet:
* not sure about the move to web3.py 5 beta vs stable
* would wait for deployed contracts to catch up (which they haven't)

**Pull request merged**
